// TODO: Substitue CSMFFormat with your actual class name
char CSMFFormat::magic(){}
int CSMFFormat::version(){}
int CSMFFormat::mapid(){}
int CSMFFormat::mapx(){}
int CSMFFormat::mapy(){}
int CSMFFormat::squareSize(){}
int CSMFFormat::texelPerSquare(){}
int CSMFFormat::tilesize(){}
float CSMFFormat::minHeight(){}
float CSMFFormat::maxHeight(){}
int CSMFFormat::heightmapPtr(){}
int CSMFFormat::typeMapPtr(){}
int CSMFFormat::tilesPtr(){}
int CSMFFormat::minimapPtr(){}
int CSMFFormat::metalmapPtr(){}
int CSMFFormat::featurePtr(){}
int CSMFFormat::numExtraHeaders(){}
int CSMFFormat::size(){}
int CSMFFormat::type(){}
int CSMFFormat::numTileFiles(){}
int CSMFFormat::numTiles(){}
int CSMFFormat::numFeatureType(){}
int CSMFFormat::numFeatures(){}
int CSMFFormat::featureType(){}
float CSMFFormat::xpos(){}
float CSMFFormat::ypos(){}
float CSMFFormat::zpos(){}
float CSMFFormat::rotation(){}
float CSMFFormat::relativeSize(){}
char CSMFFormat::magic(){}
int CSMFFormat::version(){}
int CSMFFormat::numTiles(){}
int CSMFFormat::tileSize(){}
int CSMFFormat::compressionType(){}
