// TODO: Substitue CEFXfuncs with your actual class name
LPALGENEFFECTS CEFXfuncs::alGenEffects(){}
LPALDELETEEFFECTS CEFXfuncs::alDeleteEffects(){}
LPALISEFFECT CEFXfuncs::alIsEffect(){}
LPALEFFECTI CEFXfuncs::alEffecti(){}
LPALEFFECTIV CEFXfuncs::alEffectiv(){}
LPALEFFECTF CEFXfuncs::alEffectf(){}
LPALEFFECTFV CEFXfuncs::alEffectfv(){}
LPALGETEFFECTI CEFXfuncs::alGetEffecti(){}
LPALGETEFFECTIV CEFXfuncs::alGetEffectiv(){}
LPALGETEFFECTF CEFXfuncs::alGetEffectf(){}
LPALGETEFFECTFV CEFXfuncs::alGetEffectfv(){}
LPALGENFILTERS CEFXfuncs::alGenFilters(){}
LPALDELETEFILTERS CEFXfuncs::alDeleteFilters(){}
LPALISFILTER CEFXfuncs::alIsFilter(){}
LPALFILTERI CEFXfuncs::alFilteri(){}
LPALFILTERIV CEFXfuncs::alFilteriv(){}
LPALFILTERF CEFXfuncs::alFilterf(){}
LPALFILTERFV CEFXfuncs::alFilterfv(){}
LPALGETFILTERI CEFXfuncs::alGetFilteri(){}
LPALGETFILTERIV CEFXfuncs::alGetFilteriv(){}
LPALGETFILTERF CEFXfuncs::alGetFilterf(){}
LPALGETFILTERFV CEFXfuncs::alGetFilterfv(){}
LPALGENAUXILIARYEFFECTSLOTS CEFXfuncs::alGenAuxiliaryEffectSlots(){}
LPALDELETEAUXILIARYEFFECTSLOTS CEFXfuncs::alDeleteAuxiliaryEffectSlots(){}
LPALISAUXILIARYEFFECTSLOT CEFXfuncs::alIsAuxiliaryEffectSlot(){}
LPALAUXILIARYEFFECTSLOTI CEFXfuncs::alAuxiliaryEffectSloti(){}
LPALAUXILIARYEFFECTSLOTIV CEFXfuncs::alAuxiliaryEffectSlotiv(){}
LPALAUXILIARYEFFECTSLOTF CEFXfuncs::alAuxiliaryEffectSlotf(){}
LPALAUXILIARYEFFECTSLOTFV CEFXfuncs::alAuxiliaryEffectSlotfv(){}
LPALGETAUXILIARYEFFECTSLOTI CEFXfuncs::alGetAuxiliaryEffectSloti(){}
LPALGETAUXILIARYEFFECTSLOTIV CEFXfuncs::alGetAuxiliaryEffectSlotiv(){}
LPALGETAUXILIARYEFFECTSLOTF CEFXfuncs::alGetAuxiliaryEffectSlotf(){}
LPALGETAUXILIARYEFFECTSLOTFV CEFXfuncs::alGetAuxiliaryEffectSlotfv(){}
