// TODO: Substitue CUnitDef with your actual class name
std::string CUnitDef::name(){}
q(const).WeaponDef CUnitDef::def(){}
int CUnitDef::slavedTo(){}
float CUnitDef::maxMainDirAngleDif(){}
unsigned int CUnitDef::badTargetCat(){}
unsigned int CUnitDef::onlyTargetCat(){}
float3 CUnitDef::mainDir(){}
void CUnitDef::SetNoCost(bool noCost){}
bool CUnitDef::HasBomberWeapon(){}
int CUnitDef::cobID(){}
q(const).UnitDef CUnitDef::decoyDef(){}
int CUnitDef::techLevel(){}
float CUnitDef::metalUpkeep(){}
float CUnitDef::energyUpkeep(){}
float CUnitDef::metalMake(){}
float CUnitDef::makesMetal(){}
float CUnitDef::energyMake(){}
float CUnitDef::buildTime(){}
float CUnitDef::extractsMetal(){}
float CUnitDef::extractRange(){}
float CUnitDef::windGenerator(){}
float CUnitDef::tidalGenerator(){}
float CUnitDef::metalStorage(){}
float CUnitDef::energyStorage(){}
float CUnitDef::harvestMetalStorage(){}
float CUnitDef::harvestEnergyStorage(){}
float CUnitDef::autoHeal(){}
float CUnitDef::idleAutoHeal(){}
int CUnitDef::idleTime(){}
float CUnitDef::power(){}
unsigned int CUnitDef::category(){}
float CUnitDef::speed(){}
float CUnitDef::rSpeed(){}
float CUnitDef::turnRate(){}
bool CUnitDef::turnInPlace(){}
float CUnitDef::turnInPlaceSpeedLimit(){}
float CUnitDef::turnInPlaceAngleLimit(){}
bool CUnitDef::collide(){}
float CUnitDef::losHeight(){}
float CUnitDef::radarHeight(){}
float CUnitDef::losRadius(){}
float CUnitDef::airLosRadius(){}
int CUnitDef::radarRadius(){}
int CUnitDef::sonarRadius(){}
int CUnitDef::jammerRadius(){}
int CUnitDef::sonarJamRadius(){}
int CUnitDef::seismicRadius(){}
float CUnitDef::seismicSignature(){}
bool CUnitDef::stealth(){}
bool CUnitDef::sonarStealth(){}
bool CUnitDef::buildRange3D(){}
float CUnitDef::buildDistance(){}
float CUnitDef::buildSpeed(){}
float CUnitDef::reclaimSpeed(){}
float CUnitDef::repairSpeed(){}
float CUnitDef::maxRepairSpeed(){}
float CUnitDef::resurrectSpeed(){}
float CUnitDef::captureSpeed(){}
float CUnitDef::terraformSpeed(){}
bool CUnitDef::canSubmerge(){}
bool CUnitDef::canfly(){}
bool CUnitDef::floatOnWater(){}
bool CUnitDef::pushResistant(){}
bool CUnitDef::strafeToAttack(){}
float CUnitDef::minCollisionSpeed(){}
float CUnitDef::slideTolerance(){}
float CUnitDef::maxHeightDif(){}
float CUnitDef::waterline(){}
float CUnitDef::minWaterDepth(){}
float CUnitDef::maxWaterDepth(){}
unsigned int CUnitDef::pathType(){}
float CUnitDef::armoredMultiple(){}
int CUnitDef::armorType(){}
int CUnitDef::flankingBonusMode(){}
float3 CUnitDef::flankingBonusDir(){}
float CUnitDef::flankingBonusMax(){}
float CUnitDef::flankingBonusMin(){}
float CUnitDef::flankingBonusMobilityAdd(){}
std::string CUnitDef::humanName(){}
std::string CUnitDef::decoyName(){}
std::string CUnitDef::scriptName(){}
std::string CUnitDef::tooltip(){}
std::string CUnitDef::wreckName(){}
std::string CUnitDef::categoryString(){}
std::string CUnitDef::buildPicName(){}
std::vector<(UnitDefWeapon)> CUnitDef::weapons(){}
std::vector<(YardMapStatus)> CUnitDef::yardmap(){}
std::uint16_t CUnitDef::buildingMask(){}
std::vector<(std::string)> CUnitDef::modelCEGTags(){}
std::vector<(std::string)> CUnitDef::pieceCEGTags(){}
std::vector<(unsigned int)> CUnitDef::modelExplGenIDs(){}
std::vector<(unsigned int)> CUnitDef::pieceExplGenIDs(){}
spring::unordered_map<(int,std::string)> CUnitDef::buildOptions(){}
q(const).WeaponDef CUnitDef::shieldWeaponDef(){}
q(const).WeaponDef CUnitDef::stockpileWeaponDef(){}
float CUnitDef::maxWeaponRange(){}
float CUnitDef::maxCoverage(){}
q(const).WeaponDef CUnitDef::deathExpWeaponDef(){}
q(const).WeaponDef CUnitDef::selfdExpWeaponDef(){}
UnitDefImage CUnitDef::buildPic(){}
icon::CIcon CUnitDef::iconType(){}
int CUnitDef::selfDCountdown(){}
bool CUnitDef::builder(){}
bool CUnitDef::activateWhenBuilt(){}
bool CUnitDef::onoffable(){}
bool CUnitDef::fullHealthFactory(){}
bool CUnitDef::factoryHeadingTakeoff(){}
bool CUnitDef::capturable(){}
bool CUnitDef::repairable(){}
bool CUnitDef::canmove(){}
bool CUnitDef::canAttack(){}
bool CUnitDef::canFight(){}
bool CUnitDef::canPatrol(){}
bool CUnitDef::canGuard(){}
bool CUnitDef::canRepeat(){}
bool CUnitDef::canResurrect(){}
bool CUnitDef::canCapture(){}
bool CUnitDef::canCloak(){}
bool CUnitDef::canSelfD(){}
bool CUnitDef::canKamikaze(){}
bool CUnitDef::canRestore(){}
bool CUnitDef::canRepair(){}
bool CUnitDef::canReclaim(){}
bool CUnitDef::canAssist(){}
bool CUnitDef::canBeAssisted(){}
bool CUnitDef::canSelfRepair(){}
bool CUnitDef::canFireControl(){}
bool CUnitDef::canManualFire(){}
int CUnitDef::fireState(){}
int CUnitDef::moveState(){}
float CUnitDef::wingDrag(){}
float CUnitDef::wingAngle(){}
float CUnitDef::frontToSpeed(){}
float CUnitDef::speedToFront(){}
float CUnitDef::myGravity(){}
float CUnitDef::maxBank(){}
float CUnitDef::maxPitch(){}
float CUnitDef::turnRadius(){}
float CUnitDef::wantedHeight(){}
float CUnitDef::verticalSpeed(){}
bool CUnitDef::useSmoothMesh(){}
bool CUnitDef::hoverAttack(){}
bool CUnitDef::airStrafe(){}
float CUnitDef::dlHoverFactor(){}
bool CUnitDef::bankingAllowed(){}
float CUnitDef::maxAcc(){}
float CUnitDef::maxDec(){}
float CUnitDef::maxAileron(){}
float CUnitDef::maxElevator(){}
float CUnitDef::maxRudder(){}
float CUnitDef::crashDrag(){}
float CUnitDef::loadingRadius(){}
float CUnitDef::unloadSpread(){}
int CUnitDef::transportCapacity(){}
int CUnitDef::transportSize(){}
int CUnitDef::minTransportSize(){}
bool CUnitDef::isAirBase(){}
bool CUnitDef::isFirePlatform(){}
float CUnitDef::transportMass(){}
float CUnitDef::minTransportMass(){}
bool CUnitDef::holdSteady(){}
bool CUnitDef::releaseHeld(){}
bool CUnitDef::cantBeTransported(){}
bool CUnitDef::transportByEnemy(){}
int CUnitDef::transportUnloadMethod(){}
float CUnitDef::fallSpeed(){}
float CUnitDef::unitFallSpeed(){}
bool CUnitDef::startCloaked(){}
float CUnitDef::cloakCost(){}
float CUnitDef::cloakCostMoving(){}
float CUnitDef::decloakDistance(){}
bool CUnitDef::decloakSpherical(){}
bool CUnitDef::decloakOnFire(){}
int CUnitDef::cloakTimeout(){}
float CUnitDef::kamikazeDist(){}
bool CUnitDef::kamikazeUseLOS(){}
bool CUnitDef::targfac(){}
bool CUnitDef::needGeo(){}
bool CUnitDef::isFeature(){}
bool CUnitDef::hideDamage(){}
bool CUnitDef::showPlayerName(){}
int CUnitDef::highTrajectoryType(){}
unsigned int CUnitDef::noChaseCategory(){}
UnitDef::SoundStruct CUnitDef::sounds(){}
bool CUnitDef::canDropFlare(){}
float CUnitDef::flareReloadTime(){}
float CUnitDef::flareEfficiency(){}
float CUnitDef::flareDelay(){}
float3 CUnitDef::flareDropVector(){}
int CUnitDef::flareTime(){}
int CUnitDef::flareSalvoSize(){}
int CUnitDef::flareSalvoDelay(){}
bool CUnitDef::canLoopbackAttack(){}
bool CUnitDef::levelGround(){}
bool CUnitDef::showNanoFrame(){}
bool CUnitDef::showNanoSpray(){}
float3 CUnitDef::nanoColor(){}
int CUnitDef::maxThisUnit(){}
void CUnitDef::ParseWeaponsTable(const LuaTable & weaponsTable){}
void CUnitDef::CreateYardMap(std::string yardMapStr){}
float CUnitDef::realMetalCost(){}
float CUnitDef::realEnergyCost(){}
float CUnitDef::realMetalUpkeep(){}
float CUnitDef::realEnergyUpkeep(){}
float CUnitDef::realBuildTime(){}
