// TODO: Substitue CLuaSyncedMoveCtrl with your actual class name
bool CLuaSyncedMoveCtrl::PushMoveCtrl(lua_State * L){}
bool CLuaSyncedMoveCtrl::CreateMetaTable(lua_State * L){}
bool CLuaSyncedMoveCtrl::CreateMoveCtrl(lua_State * L, CUnit * unit){}
int CLuaSyncedMoveCtrl::IsEnabled(lua_State * L){}
int CLuaSyncedMoveCtrl::Enable(lua_State * L){}
int CLuaSyncedMoveCtrl::Disable(lua_State * L){}
int CLuaSyncedMoveCtrl::SetTag(lua_State * L){}
int CLuaSyncedMoveCtrl::GetTag(lua_State * L){}
int CLuaSyncedMoveCtrl::SetProgressState(lua_State * L){}
int CLuaSyncedMoveCtrl::SetExtrapolate(lua_State * L){}
int CLuaSyncedMoveCtrl::SetRelativeVelocity(lua_State * L){}
int CLuaSyncedMoveCtrl::SetPhysics(lua_State * L){}
int CLuaSyncedMoveCtrl::SetPosition(lua_State * L){}
int CLuaSyncedMoveCtrl::SetVelocity(lua_State * L){}
int CLuaSyncedMoveCtrl::SetRotation(lua_State * L){}
int CLuaSyncedMoveCtrl::SetRotationOffset(lua_State * L){}
int CLuaSyncedMoveCtrl::SetRotationVelocity(lua_State * L){}
int CLuaSyncedMoveCtrl::SetHeading(lua_State * L){}
int CLuaSyncedMoveCtrl::SetTrackSlope(lua_State * L){}
int CLuaSyncedMoveCtrl::SetTrackGround(lua_State * L){}
int CLuaSyncedMoveCtrl::SetGroundOffset(lua_State * L){}
int CLuaSyncedMoveCtrl::SetGravity(lua_State * L){}
int CLuaSyncedMoveCtrl::SetDrag(lua_State * L){}
int CLuaSyncedMoveCtrl::SetWindFactor(lua_State * L){}
int CLuaSyncedMoveCtrl::SetLimits(lua_State * L){}
int CLuaSyncedMoveCtrl::SetNoBlocking(lua_State * L){}
int CLuaSyncedMoveCtrl::SetShotStop(lua_State * L){}
int CLuaSyncedMoveCtrl::SetSlopeStop(lua_State * L){}
int CLuaSyncedMoveCtrl::SetCollideStop(lua_State * L){}
int CLuaSyncedMoveCtrl::SetGroundMoveTypeData(lua_State * L){}
int CLuaSyncedMoveCtrl::SetAirMoveTypeData(lua_State * L){}
int CLuaSyncedMoveCtrl::SetGunshipMoveTypeData(lua_State * L){}
int CLuaSyncedMoveCtrl::SetBaseMoveTypeData(lua_State * L){}
int CLuaSyncedMoveCtrl::SetMoveDef(lua_State * L){}
