// TODO: Substitue CLuaSyncedCtrl with your actual class name
bool CLuaSyncedCtrl::PushEntries(lua_State * L){}
void CLuaSyncedCtrl::CheckAllowGameChanges(lua_State * L){}
bool CLuaSyncedCtrl::inCreateUnit(){}
bool CLuaSyncedCtrl::inDestroyUnit(){}
bool CLuaSyncedCtrl::inTransferUnit(){}
bool CLuaSyncedCtrl::inCreateFeature(){}
bool CLuaSyncedCtrl::inDestroyFeature(){}
bool CLuaSyncedCtrl::inGiveOrder(){}
bool CLuaSyncedCtrl::inHeightMap(){}
bool CLuaSyncedCtrl::inSmoothMesh(){}
int CLuaSyncedCtrl::SetAlly(lua_State * L){}
int CLuaSyncedCtrl::KillTeam(lua_State * L){}
int CLuaSyncedCtrl::AssignPlayerToTeam(lua_State * L){}
int CLuaSyncedCtrl::GameOver(lua_State * L){}
int CLuaSyncedCtrl::SetGlobalLos(lua_State * L){}
int CLuaSyncedCtrl::AddTeamResource(lua_State * L){}
int CLuaSyncedCtrl::UseTeamResource(lua_State * L){}
int CLuaSyncedCtrl::SetTeamResource(lua_State * L){}
int CLuaSyncedCtrl::SetTeamShareLevel(lua_State * L){}
int CLuaSyncedCtrl::ShareTeamResource(lua_State * L){}
int CLuaSyncedCtrl::CallCOBScript(lua_State * L){}
int CLuaSyncedCtrl::GetCOBScriptID(lua_State * L){}
int CLuaSyncedCtrl::SetGameRulesParam(lua_State * L){}
int CLuaSyncedCtrl::SetTeamRulesParam(lua_State * L){}
int CLuaSyncedCtrl::SetUnitRulesParam(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureRulesParam(lua_State * L){}
int CLuaSyncedCtrl::GiveOrderToUnit(lua_State * L){}
int CLuaSyncedCtrl::GiveOrderToUnitMap(lua_State * L){}
int CLuaSyncedCtrl::GiveOrderToUnitArray(lua_State * L){}
int CLuaSyncedCtrl::GiveOrderArrayToUnitMap(lua_State * L){}
int CLuaSyncedCtrl::GiveOrderArrayToUnitArray(lua_State * L){}
int CLuaSyncedCtrl::CreateUnit(lua_State * L){}
int CLuaSyncedCtrl::DestroyUnit(lua_State * L){}
int CLuaSyncedCtrl::TransferUnit(lua_State * L){}
int CLuaSyncedCtrl::CreateFeature(lua_State * L){}
int CLuaSyncedCtrl::DestroyFeature(lua_State * L){}
int CLuaSyncedCtrl::TransferFeature(lua_State * L){}
int CLuaSyncedCtrl::SetUnitCosts(lua_State * L){}
int CLuaSyncedCtrl::SetUnitTooltip(lua_State * L){}
int CLuaSyncedCtrl::SetUnitHealth(lua_State * L){}
int CLuaSyncedCtrl::SetUnitMaxHealth(lua_State * L){}
int CLuaSyncedCtrl::SetUnitStockpile(lua_State * L){}
int CLuaSyncedCtrl::SetUnitWeaponState(lua_State * L){}
int CLuaSyncedCtrl::SetUnitWeaponDamages(lua_State * L){}
int CLuaSyncedCtrl::SetUnitMaxRange(lua_State * L){}
int CLuaSyncedCtrl::SetUnitExperience(lua_State * L){}
int CLuaSyncedCtrl::SetUnitArmored(lua_State * L){}
int CLuaSyncedCtrl::SetUnitLosMask(lua_State * L){}
int CLuaSyncedCtrl::SetUnitLosState(lua_State * L){}
int CLuaSyncedCtrl::SetUnitCloak(lua_State * L){}
int CLuaSyncedCtrl::SetUnitStealth(lua_State * L){}
int CLuaSyncedCtrl::SetUnitSonarStealth(lua_State * L){}
int CLuaSyncedCtrl::SetUnitAlwaysVisible(lua_State * L){}
int CLuaSyncedCtrl::SetUnitResourcing(lua_State * L){}
int CLuaSyncedCtrl::SetUnitMetalExtraction(lua_State * L){}
int CLuaSyncedCtrl::SetUnitHarvestStorage(lua_State * L){}
int CLuaSyncedCtrl::SetUnitBuildSpeed(lua_State * L){}
int CLuaSyncedCtrl::SetUnitNanoPieces(lua_State * L){}
int CLuaSyncedCtrl::SetUnitBlocking(lua_State * L){}
int CLuaSyncedCtrl::SetUnitCrashing(lua_State * L){}
int CLuaSyncedCtrl::SetUnitShieldState(lua_State * L){}
int CLuaSyncedCtrl::SetUnitFlanking(lua_State * L){}
int CLuaSyncedCtrl::SetUnitTravel(lua_State * L){}
int CLuaSyncedCtrl::SetUnitFuel(lua_State * L){}
int CLuaSyncedCtrl::SetUnitMoveGoal(lua_State * L){}
int CLuaSyncedCtrl::SetUnitLandGoal(lua_State * L){}
int CLuaSyncedCtrl::ClearUnitGoal(lua_State * L){}
int CLuaSyncedCtrl::SetUnitNeutral(lua_State * L){}
int CLuaSyncedCtrl::SetUnitTarget(lua_State * L){}
int CLuaSyncedCtrl::SetUnitMidAndAimPos(lua_State * L){}
int CLuaSyncedCtrl::SetUnitRadiusAndHeight(lua_State * L){}
int CLuaSyncedCtrl::SetUnitCollisionVolumeData(lua_State * L){}
int CLuaSyncedCtrl::SetUnitPieceCollisionVolumeData(lua_State * L){}
int CLuaSyncedCtrl::SetUnitPieceParent(lua_State * L){}
int CLuaSyncedCtrl::SetUnitPieceMatrix(lua_State * L){}
int CLuaSyncedCtrl::SetUnitSensorRadius(lua_State * L){}
int CLuaSyncedCtrl::SetUnitPosErrorParams(lua_State * L){}
int CLuaSyncedCtrl::SetUnitPhysics(lua_State * L){}
int CLuaSyncedCtrl::SetUnitMass(lua_State * L){}
int CLuaSyncedCtrl::SetUnitPosition(lua_State * L){}
int CLuaSyncedCtrl::SetUnitRotation(lua_State * L){}
int CLuaSyncedCtrl::SetUnitDirection(lua_State * L){}
int CLuaSyncedCtrl::SetUnitVelocity(lua_State * L){}
int CLuaSyncedCtrl::AddUnitDamage(lua_State * L){}
int CLuaSyncedCtrl::AddUnitImpulse(lua_State * L){}
int CLuaSyncedCtrl::AddUnitSeismicPing(lua_State * L){}
int CLuaSyncedCtrl::AddUnitResource(lua_State * L){}
int CLuaSyncedCtrl::UseUnitResource(lua_State * L){}
int CLuaSyncedCtrl::RemoveBuildingDecal(lua_State * L){}
int CLuaSyncedCtrl::AddGrass(lua_State * L){}
int CLuaSyncedCtrl::RemoveGrass(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureAlwaysVisible(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureHealth(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureMaxHealth(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureReclaim(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureResources(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureResurrect(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureMoveCtrl(lua_State * L){}
int CLuaSyncedCtrl::SetFeaturePhysics(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureMass(lua_State * L){}
int CLuaSyncedCtrl::SetFeaturePosition(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureRotation(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureDirection(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureVelocity(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureBlocking(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureNoSelect(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureMidAndAimPos(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureRadiusAndHeight(lua_State * L){}
int CLuaSyncedCtrl::SetFeatureCollisionVolumeData(lua_State * L){}
int CLuaSyncedCtrl::SetFeaturePieceCollisionVolumeData(lua_State * L){}
int CLuaSyncedCtrl::SetProjectileAlwaysVisible(lua_State * L){}
int CLuaSyncedCtrl::SetProjectileMoveControl(lua_State * L){}
int CLuaSyncedCtrl::SetProjectilePosition(lua_State * L){}
int CLuaSyncedCtrl::SetProjectileVelocity(lua_State * L){}
int CLuaSyncedCtrl::SetProjectileCollision(lua_State * L){}
int CLuaSyncedCtrl::SetProjectileTarget(lua_State * L){}
int CLuaSyncedCtrl::SetProjectileIsIntercepted(lua_State * L){}
int CLuaSyncedCtrl::SetProjectileDamages(lua_State * L){}
int CLuaSyncedCtrl::SetProjectileIgnoreTrackingError(lua_State * L){}
int CLuaSyncedCtrl::SetProjectileGravity(lua_State * L){}
int CLuaSyncedCtrl::SetProjectileSpinAngle(lua_State * L){}
int CLuaSyncedCtrl::SetProjectileSpinSpeed(lua_State * L){}
int CLuaSyncedCtrl::SetProjectileSpinVec(lua_State * L){}
int CLuaSyncedCtrl::SetPieceProjectileParams(lua_State * L){}
int CLuaSyncedCtrl::SetProjectileCEG(lua_State * L){}
int CLuaSyncedCtrl::LevelHeightMap(lua_State * L){}
int CLuaSyncedCtrl::AdjustHeightMap(lua_State * L){}
int CLuaSyncedCtrl::RevertHeightMap(lua_State * L){}
int CLuaSyncedCtrl::AddHeightMap(lua_State * L){}
int CLuaSyncedCtrl::SetHeightMap(lua_State * L){}
int CLuaSyncedCtrl::SetHeightMapFunc(lua_State * L){}
int CLuaSyncedCtrl::LevelSmoothMesh(lua_State * L){}
int CLuaSyncedCtrl::AdjustSmoothMesh(lua_State * L){}
int CLuaSyncedCtrl::RevertSmoothMesh(lua_State * L){}
int CLuaSyncedCtrl::AddSmoothMesh(lua_State * L){}
int CLuaSyncedCtrl::SetSmoothMesh(lua_State * L){}
int CLuaSyncedCtrl::SetSmoothMeshFunc(lua_State * L){}
int CLuaSyncedCtrl::SetMapSquareTerrainType(lua_State * L){}
int CLuaSyncedCtrl::SetTerrainTypeData(lua_State * L){}
int CLuaSyncedCtrl::SetSquareBuildingMask(lua_State * L){}
int CLuaSyncedCtrl::UnitWeaponFire(lua_State * L){}
int CLuaSyncedCtrl::UnitWeaponHoldFire(lua_State * L){}
int CLuaSyncedCtrl::UnitAttach(lua_State * L){}
int CLuaSyncedCtrl::UnitDetach(lua_State * L){}
int CLuaSyncedCtrl::UnitDetachFromAir(lua_State * L){}
int CLuaSyncedCtrl::SetUnitLoadingTransport(lua_State * L){}
int CLuaSyncedCtrl::SpawnProjectile(lua_State * L){}
int CLuaSyncedCtrl::DeleteProjectile(lua_State * L){}
int CLuaSyncedCtrl::SpawnExplosion(lua_State * L){}
int CLuaSyncedCtrl::SpawnCEG(lua_State * L){}
int CLuaSyncedCtrl::SpawnSFX(lua_State * L){}
int CLuaSyncedCtrl::EditUnitCmdDesc(lua_State * L){}
int CLuaSyncedCtrl::InsertUnitCmdDesc(lua_State * L){}
int CLuaSyncedCtrl::RemoveUnitCmdDesc(lua_State * L){}
int CLuaSyncedCtrl::SetNoPause(lua_State * L){}
int CLuaSyncedCtrl::SetUnitToFeature(lua_State * L){}
int CLuaSyncedCtrl::SetExperienceGrade(lua_State * L){}
int CLuaSyncedCtrl::SetRadarErrorParams(lua_State * L){}
