// TODO: Substitue CLuaSyncedRead with your actual class name
bool CLuaSyncedRead::PushEntries(lua_State * L){}
void CLuaSyncedRead::AllowGameChanges(bool value){}
int CLuaSyncedRead::GetMapOptions(lua_State * L){}
int CLuaSyncedRead::GetModOptions(lua_State * L){}
int CLuaSyncedRead::IsCheatingEnabled(lua_State * L){}
int CLuaSyncedRead::IsGodModeEnabled(lua_State * L){}
int CLuaSyncedRead::IsDevLuaEnabled(lua_State * L){}
int CLuaSyncedRead::IsEditDefsEnabled(lua_State * L){}
int CLuaSyncedRead::AreHelperAIsEnabled(lua_State * L){}
int CLuaSyncedRead::FixedAllies(lua_State * L){}
int CLuaSyncedRead::IsGameOver(lua_State * L){}
int CLuaSyncedRead::GetGaiaTeamID(lua_State * L){}
int CLuaSyncedRead::GetGameFrame(lua_State * L){}
int CLuaSyncedRead::GetGameSeconds(lua_State * L){}
int CLuaSyncedRead::GetGameRulesParam(lua_State * L){}
int CLuaSyncedRead::GetGameRulesParams(lua_State * L){}
int CLuaSyncedRead::GetWind(lua_State * L){}
int CLuaSyncedRead::GetHeadingFromVector(lua_State * L){}
int CLuaSyncedRead::GetVectorFromHeading(lua_State * L){}
int CLuaSyncedRead::GetSideData(lua_State * L){}
int CLuaSyncedRead::GetAllyTeamStartBox(lua_State * L){}
int CLuaSyncedRead::GetTeamStartPosition(lua_State * L){}
int CLuaSyncedRead::GetAllyTeamList(lua_State * L){}
int CLuaSyncedRead::GetTeamList(lua_State * L){}
int CLuaSyncedRead::GetPlayerList(lua_State * L){}
int CLuaSyncedRead::GetPlayerInfo(lua_State * L){}
int CLuaSyncedRead::GetPlayerControlledUnit(lua_State * L){}
int CLuaSyncedRead::GetAIInfo(lua_State * L){}
int CLuaSyncedRead::GetTeamInfo(lua_State * L){}
int CLuaSyncedRead::GetTeamResources(lua_State * L){}
int CLuaSyncedRead::GetTeamUnitStats(lua_State * L){}
int CLuaSyncedRead::GetTeamResourceStats(lua_State * L){}
int CLuaSyncedRead::GetTeamRulesParam(lua_State * L){}
int CLuaSyncedRead::GetTeamRulesParams(lua_State * L){}
int CLuaSyncedRead::GetTeamStatsHistory(lua_State * L){}
int CLuaSyncedRead::GetTeamLuaAI(lua_State * L){}
int CLuaSyncedRead::GetAllyTeamInfo(lua_State * L){}
int CLuaSyncedRead::AreTeamsAllied(lua_State * L){}
int CLuaSyncedRead::ArePlayersAllied(lua_State * L){}
int CLuaSyncedRead::GetAllUnits(lua_State * L){}
int CLuaSyncedRead::GetTeamUnits(lua_State * L){}
int CLuaSyncedRead::GetTeamUnitsSorted(lua_State * L){}
int CLuaSyncedRead::GetTeamUnitsCounts(lua_State * L){}
int CLuaSyncedRead::GetTeamUnitsByDefs(lua_State * L){}
int CLuaSyncedRead::GetTeamUnitDefCount(lua_State * L){}
int CLuaSyncedRead::GetTeamUnitCount(lua_State * L){}
int CLuaSyncedRead::GetUnitsInRectangle(lua_State * L){}
int CLuaSyncedRead::GetUnitsInBox(lua_State * L){}
int CLuaSyncedRead::GetUnitsInPlanes(lua_State * L){}
int CLuaSyncedRead::GetUnitsInSphere(lua_State * L){}
int CLuaSyncedRead::GetUnitsInCylinder(lua_State * L){}
int CLuaSyncedRead::GetUnitNearestAlly(lua_State * L){}
int CLuaSyncedRead::GetUnitNearestEnemy(lua_State * L){}
int CLuaSyncedRead::GetFeaturesInRectangle(lua_State * L){}
int CLuaSyncedRead::GetFeaturesInSphere(lua_State * L){}
int CLuaSyncedRead::GetFeaturesInCylinder(lua_State * L){}
int CLuaSyncedRead::GetProjectilesInRectangle(lua_State * L){}
int CLuaSyncedRead::ValidUnitID(lua_State * L){}
int CLuaSyncedRead::GetUnitTooltip(lua_State * L){}
int CLuaSyncedRead::GetUnitDefID(lua_State * L){}
int CLuaSyncedRead::GetUnitTeam(lua_State * L){}
int CLuaSyncedRead::GetUnitAllyTeam(lua_State * L){}
int CLuaSyncedRead::GetUnitNeutral(lua_State * L){}
int CLuaSyncedRead::GetUnitHealth(lua_State * L){}
int CLuaSyncedRead::GetUnitIsDead(lua_State * L){}
int CLuaSyncedRead::GetUnitIsStunned(lua_State * L){}
int CLuaSyncedRead::GetUnitResources(lua_State * L){}
int CLuaSyncedRead::GetUnitMetalExtraction(lua_State * L){}
int CLuaSyncedRead::GetUnitExperience(lua_State * L){}
int CLuaSyncedRead::GetUnitStates(lua_State * L){}
int CLuaSyncedRead::GetUnitArmored(lua_State * L){}
int CLuaSyncedRead::GetUnitIsActive(lua_State * L){}
int CLuaSyncedRead::GetUnitIsCloaked(lua_State * L){}
int CLuaSyncedRead::GetUnitSelfDTime(lua_State * L){}
int CLuaSyncedRead::GetUnitStockpile(lua_State * L){}
int CLuaSyncedRead::GetUnitSensorRadius(lua_State * L){}
int CLuaSyncedRead::GetUnitPosErrorParams(lua_State * L){}
int CLuaSyncedRead::GetUnitHeight(lua_State * L){}
int CLuaSyncedRead::GetUnitRadius(lua_State * L){}
int CLuaSyncedRead::GetUnitMass(lua_State * L){}
int CLuaSyncedRead::GetUnitPosition(lua_State * L){}
int CLuaSyncedRead::GetUnitBasePosition(lua_State * L){}
int CLuaSyncedRead::GetUnitVectors(lua_State * L){}
int CLuaSyncedRead::GetUnitRotation(lua_State * L){}
int CLuaSyncedRead::GetUnitDirection(lua_State * L){}
int CLuaSyncedRead::GetUnitHeading(lua_State * L){}
int CLuaSyncedRead::GetUnitVelocity(lua_State * L){}
int CLuaSyncedRead::GetUnitBuildFacing(lua_State * L){}
int CLuaSyncedRead::GetUnitIsBuilding(lua_State * L){}
int CLuaSyncedRead::GetUnitCurrentBuildPower(lua_State * L){}
int CLuaSyncedRead::GetUnitHarvestStorage(lua_State * L){}
int CLuaSyncedRead::GetUnitNanoPieces(lua_State * L){}
int CLuaSyncedRead::GetUnitTransporter(lua_State * L){}
int CLuaSyncedRead::GetUnitIsTransporting(lua_State * L){}
int CLuaSyncedRead::GetUnitShieldState(lua_State * L){}
int CLuaSyncedRead::GetUnitFlanking(lua_State * L){}
int CLuaSyncedRead::GetUnitMaxRange(lua_State * L){}
int CLuaSyncedRead::GetUnitWeaponState(lua_State * L){}
int CLuaSyncedRead::GetUnitWeaponDamages(lua_State * L){}
int CLuaSyncedRead::GetUnitWeaponVectors(lua_State * L){}
int CLuaSyncedRead::GetUnitWeaponTryTarget(lua_State * L){}
int CLuaSyncedRead::GetUnitWeaponTestTarget(lua_State * L){}
int CLuaSyncedRead::GetUnitWeaponTestRange(lua_State * L){}
int CLuaSyncedRead::GetUnitWeaponHaveFreeLineOfFire(lua_State * L){}
int CLuaSyncedRead::GetUnitWeaponCanFire(lua_State * L){}
int CLuaSyncedRead::GetUnitWeaponTarget(lua_State * L){}
int CLuaSyncedRead::GetUnitTravel(lua_State * L){}
int CLuaSyncedRead::GetUnitFuel(lua_State * L){}
int CLuaSyncedRead::GetUnitEstimatedPath(lua_State * L){}
int CLuaSyncedRead::GetUnitLastAttacker(lua_State * L){}
int CLuaSyncedRead::GetUnitLastAttackedPiece(lua_State * L){}
int CLuaSyncedRead::GetUnitCollisionVolumeData(lua_State * L){}
int CLuaSyncedRead::GetUnitPieceCollisionVolumeData(lua_State * L){}
int CLuaSyncedRead::GetUnitBlocking(lua_State * L){}
int CLuaSyncedRead::GetUnitMoveTypeData(lua_State * L){}
int CLuaSyncedRead::GetUnitCommands(lua_State * L){}
int CLuaSyncedRead::GetFactoryCounts(lua_State * L){}
int CLuaSyncedRead::GetFactoryCommands(lua_State * L){}
int CLuaSyncedRead::GetCommandQueue(lua_State * L){}
int CLuaSyncedRead::GetFullBuildQueue(lua_State * L){}
int CLuaSyncedRead::GetRealBuildQueue(lua_State * L){}
int CLuaSyncedRead::GetUnitCmdDescs(lua_State * L){}
int CLuaSyncedRead::FindUnitCmdDesc(lua_State * L){}
int CLuaSyncedRead::GetUnitRulesParam(lua_State * L){}
int CLuaSyncedRead::GetUnitRulesParams(lua_State * L){}
int CLuaSyncedRead::GetUnitLosState(lua_State * L){}
int CLuaSyncedRead::GetUnitSeparation(lua_State * L){}
int CLuaSyncedRead::GetUnitFeatureSeparation(lua_State * L){}
int CLuaSyncedRead::GetUnitDefDimensions(lua_State * L){}
int CLuaSyncedRead::GetAllFeatures(lua_State * L){}
int CLuaSyncedRead::ValidFeatureID(lua_State * L){}
int CLuaSyncedRead::GetFeatureDefID(lua_State * L){}
int CLuaSyncedRead::GetFeatureTeam(lua_State * L){}
int CLuaSyncedRead::GetFeatureAllyTeam(lua_State * L){}
int CLuaSyncedRead::GetFeatureHealth(lua_State * L){}
int CLuaSyncedRead::GetFeatureHeight(lua_State * L){}
int CLuaSyncedRead::GetFeatureRadius(lua_State * L){}
int CLuaSyncedRead::GetFeatureMass(lua_State * L){}
int CLuaSyncedRead::GetFeaturePosition(lua_State * L){}
int CLuaSyncedRead::GetFeatureSeparation(lua_State * L){}
int CLuaSyncedRead::GetFeatureRotation(lua_State * L){}
int CLuaSyncedRead::GetFeatureDirection(lua_State * L){}
int CLuaSyncedRead::GetFeatureVelocity(lua_State * L){}
int CLuaSyncedRead::GetFeatureHeading(lua_State * L){}
int CLuaSyncedRead::GetFeatureResources(lua_State * L){}
int CLuaSyncedRead::GetFeatureBlocking(lua_State * L){}
int CLuaSyncedRead::GetFeatureNoSelect(lua_State * L){}
int CLuaSyncedRead::GetFeatureResurrect(lua_State * L){}
int CLuaSyncedRead::GetFeatureLastAttackedPiece(lua_State * L){}
int CLuaSyncedRead::GetFeatureCollisionVolumeData(lua_State * L){}
int CLuaSyncedRead::GetFeaturePieceCollisionVolumeData(lua_State * L){}
int CLuaSyncedRead::GetFeatureRulesParam(lua_State * L){}
int CLuaSyncedRead::GetFeatureRulesParams(lua_State * L){}
int CLuaSyncedRead::GetProjectilePosition(lua_State * L){}
int CLuaSyncedRead::GetProjectileDirection(lua_State * L){}
int CLuaSyncedRead::GetProjectileVelocity(lua_State * L){}
int CLuaSyncedRead::GetProjectileGravity(lua_State * L){}
int CLuaSyncedRead::GetProjectileSpinAngle(lua_State * L){}
int CLuaSyncedRead::GetProjectileSpinSpeed(lua_State * L){}
int CLuaSyncedRead::GetProjectileSpinVec(lua_State * L){}
int CLuaSyncedRead::GetPieceProjectileParams(lua_State * L){}
int CLuaSyncedRead::GetProjectileTarget(lua_State * L){}
int CLuaSyncedRead::GetProjectileIsIntercepted(lua_State * L){}
int CLuaSyncedRead::GetProjectileTimeToLive(lua_State * L){}
int CLuaSyncedRead::GetProjectileOwnerID(lua_State * L){}
int CLuaSyncedRead::GetProjectileTeamID(lua_State * L){}
int CLuaSyncedRead::GetProjectileType(lua_State * L){}
int CLuaSyncedRead::GetProjectileDefID(lua_State * L){}
int CLuaSyncedRead::GetProjectileDamages(lua_State * L){}
int CLuaSyncedRead::GetProjectileName(lua_State * L){}
int CLuaSyncedRead::GetGroundHeight(lua_State * L){}
int CLuaSyncedRead::GetGroundOrigHeight(lua_State * L){}
int CLuaSyncedRead::GetGroundNormal(lua_State * L){}
int CLuaSyncedRead::GetGroundInfo(lua_State * L){}
int CLuaSyncedRead::GetGroundBlocked(lua_State * L){}
int CLuaSyncedRead::GetGroundExtremes(lua_State * L){}
int CLuaSyncedRead::GetTerrainTypeData(lua_State * L){}
int CLuaSyncedRead::GetGrass(lua_State * L){}
int CLuaSyncedRead::GetSmoothMeshHeight(lua_State * L){}
int CLuaSyncedRead::TestMoveOrder(lua_State * L){}
int CLuaSyncedRead::TestBuildOrder(lua_State * L){}
int CLuaSyncedRead::Pos2BuildPos(lua_State * L){}
int CLuaSyncedRead::GetPositionLosState(lua_State * L){}
int CLuaSyncedRead::IsPosInLos(lua_State * L){}
int CLuaSyncedRead::IsPosInRadar(lua_State * L){}
int CLuaSyncedRead::IsPosInAirLos(lua_State * L){}
int CLuaSyncedRead::IsUnitInLos(lua_State * L){}
int CLuaSyncedRead::IsUnitInAirLos(lua_State * L){}
int CLuaSyncedRead::IsUnitInRadar(lua_State * L){}
int CLuaSyncedRead::IsUnitInJammer(lua_State * L){}
int CLuaSyncedRead::GetClosestValidPosition(lua_State * L){}
int CLuaSyncedRead::GetUnitPieceMap(lua_State * L){}
int CLuaSyncedRead::GetUnitPieceList(lua_State * L){}
int CLuaSyncedRead::GetUnitPieceInfo(lua_State * L){}
int CLuaSyncedRead::GetUnitPiecePosition(lua_State * L){}
int CLuaSyncedRead::GetUnitPieceDirection(lua_State * L){}
int CLuaSyncedRead::GetUnitPiecePosDir(lua_State * L){}
int CLuaSyncedRead::GetUnitPieceMatrix(lua_State * L){}
int CLuaSyncedRead::GetUnitScriptPiece(lua_State * L){}
int CLuaSyncedRead::GetUnitScriptNames(lua_State * L){}
int CLuaSyncedRead::GetFeaturePieceMap(lua_State * L){}
int CLuaSyncedRead::GetFeaturePieceList(lua_State * L){}
int CLuaSyncedRead::GetFeaturePieceInfo(lua_State * L){}
int CLuaSyncedRead::GetFeaturePiecePosition(lua_State * L){}
int CLuaSyncedRead::GetFeaturePieceDirection(lua_State * L){}
int CLuaSyncedRead::GetFeaturePiecePosDir(lua_State * L){}
int CLuaSyncedRead::GetFeaturePieceMatrix(lua_State * L){}
int CLuaSyncedRead::GetRadarErrorParams(lua_State * L){}
int CLuaSyncedRead::TraceRay(lua_State * L){}
int CLuaSyncedRead::TraceRayUnits(lua_State * L){}
int CLuaSyncedRead::TraceRayFeatures(lua_State * L){}
int CLuaSyncedRead::TraceRayGround(lua_State * L){}
