// TODO: Substitue CLuaUnsyncedCtrl with your actual class name
bool CLuaUnsyncedCtrl::PushEntries(lua_State * L){}
int CLuaUnsyncedCtrl::Echo(lua_State * L){}
int CLuaUnsyncedCtrl::Log(lua_State * L){}
int CLuaUnsyncedCtrl::SendMessage(lua_State * L){}
int CLuaUnsyncedCtrl::SendMessageToPlayer(lua_State * L){}
int CLuaUnsyncedCtrl::SendMessageToTeam(lua_State * L){}
int CLuaUnsyncedCtrl::SendMessageToAllyTeam(lua_State * L){}
int CLuaUnsyncedCtrl::SendMessageToSpectators(lua_State * L){}
int CLuaUnsyncedCtrl::LoadSoundDef(lua_State * L){}
int CLuaUnsyncedCtrl::PlaySoundFile(lua_State * L){}
int CLuaUnsyncedCtrl::PlaySoundStream(lua_State * L){}
int CLuaUnsyncedCtrl::StopSoundStream(lua_State * L){}
int CLuaUnsyncedCtrl::PauseSoundStream(lua_State * L){}
int CLuaUnsyncedCtrl::SetSoundStreamVolume(lua_State * L){}
int CLuaUnsyncedCtrl::SetCameraState(lua_State * L){}
int CLuaUnsyncedCtrl::SetCameraTarget(lua_State * L){}
int CLuaUnsyncedCtrl::SelectUnitMap(lua_State * L){}
int CLuaUnsyncedCtrl::SelectUnitArray(lua_State * L){}
int CLuaUnsyncedCtrl::AddWorldIcon(lua_State * L){}
int CLuaUnsyncedCtrl::AddWorldText(lua_State * L){}
int CLuaUnsyncedCtrl::AddWorldUnit(lua_State * L){}
int CLuaUnsyncedCtrl::DrawUnitCommands(lua_State * L){}
int CLuaUnsyncedCtrl::SetTeamColor(lua_State * L){}
int CLuaUnsyncedCtrl::AssignMouseCursor(lua_State * L){}
int CLuaUnsyncedCtrl::ReplaceMouseCursor(lua_State * L){}
int CLuaUnsyncedCtrl::SetCustomCommandDrawData(lua_State * L){}
int CLuaUnsyncedCtrl::SetDrawSky(lua_State * L){}
int CLuaUnsyncedCtrl::SetDrawWater(lua_State * L){}
int CLuaUnsyncedCtrl::SetDrawGround(lua_State * L){}
int CLuaUnsyncedCtrl::SetDrawGroundDeferred(lua_State * L){}
int CLuaUnsyncedCtrl::SetDrawModelsDeferred(lua_State * L){}
int CLuaUnsyncedCtrl::SetVideoCapturingMode(lua_State * L){}
int CLuaUnsyncedCtrl::SetWaterParams(lua_State * L){}
int CLuaUnsyncedCtrl::SetSoundEffectParams(lua_State * L){}
int CLuaUnsyncedCtrl::AddMapLight(lua_State * L){}
int CLuaUnsyncedCtrl::AddModelLight(lua_State * L){}
int CLuaUnsyncedCtrl::UpdateMapLight(lua_State * L){}
int CLuaUnsyncedCtrl::UpdateModelLight(lua_State * L){}
int CLuaUnsyncedCtrl::SetMapLightTrackingState(lua_State * L){}
int CLuaUnsyncedCtrl::SetModelLightTrackingState(lua_State * L){}
int CLuaUnsyncedCtrl::SetMapShader(lua_State * L){}
int CLuaUnsyncedCtrl::SetMapSquareTexture(lua_State * L){}
int CLuaUnsyncedCtrl::SetMapShadingTexture(lua_State * L){}
int CLuaUnsyncedCtrl::SetSkyBoxTexture(lua_State * L){}
int CLuaUnsyncedCtrl::SetUnitNoDraw(lua_State * L){}
int CLuaUnsyncedCtrl::SetUnitNoMinimap(lua_State * L){}
int CLuaUnsyncedCtrl::SetUnitNoSelect(lua_State * L){}
int CLuaUnsyncedCtrl::SetUnitLeaveTracks(lua_State * L){}
int CLuaUnsyncedCtrl::SetUnitSelectionVolumeData(lua_State * L){}
int CLuaUnsyncedCtrl::SetFeatureNoDraw(lua_State * L){}
int CLuaUnsyncedCtrl::SetFeatureFade(lua_State * L){}
int CLuaUnsyncedCtrl::SetFeatureSelectionVolumeData(lua_State * L){}
int CLuaUnsyncedCtrl::AddUnitIcon(lua_State * L){}
int CLuaUnsyncedCtrl::FreeUnitIcon(lua_State * L){}
int CLuaUnsyncedCtrl::ExtractModArchiveFile(lua_State * L){}
int CLuaUnsyncedCtrl::GetConfigInt(lua_State * L){}
int CLuaUnsyncedCtrl::SetConfigInt(lua_State * L){}
int CLuaUnsyncedCtrl::GetConfigFloat(lua_State * L){}
int CLuaUnsyncedCtrl::SetConfigFloat(lua_State * L){}
int CLuaUnsyncedCtrl::GetConfigString(lua_State * L){}
int CLuaUnsyncedCtrl::SetConfigString(lua_State * L){}
int CLuaUnsyncedCtrl::CreateDir(lua_State * L){}
int CLuaUnsyncedCtrl::Reload(lua_State * L){}
int CLuaUnsyncedCtrl::Restart(lua_State * L){}
int CLuaUnsyncedCtrl::Start(lua_State * L){}
int CLuaUnsyncedCtrl::Quit(lua_State * L){}
int CLuaUnsyncedCtrl::SetWMIcon(lua_State * L){}
int CLuaUnsyncedCtrl::SetWMCaption(lua_State * L){}
int CLuaUnsyncedCtrl::SetUnitDefIcon(lua_State * L){}
int CLuaUnsyncedCtrl::SetUnitDefImage(lua_State * L){}
int CLuaUnsyncedCtrl::SetActiveCommand(lua_State * L){}
int CLuaUnsyncedCtrl::LoadCmdColorsConfig(lua_State * L){}
int CLuaUnsyncedCtrl::LoadCtrlPanelConfig(lua_State * L){}
int CLuaUnsyncedCtrl::ForceLayoutUpdate(lua_State * L){}
int CLuaUnsyncedCtrl::SetLosViewColors(lua_State * L){}
int CLuaUnsyncedCtrl::WarpMouse(lua_State * L){}
int CLuaUnsyncedCtrl::SetMouseCursor(lua_State * L){}
int CLuaUnsyncedCtrl::SetClipboard(lua_State * L){}
int CLuaUnsyncedCtrl::SetCameraOffset(lua_State * L){}
int CLuaUnsyncedCtrl::SendCommands(lua_State * L){}
int CLuaUnsyncedCtrl::SetShareLevel(lua_State * L){}
int CLuaUnsyncedCtrl::ShareResources(lua_State * L){}
int CLuaUnsyncedCtrl::SetUnitGroup(lua_State * L){}
int CLuaUnsyncedCtrl::GiveOrder(lua_State * L){}
int CLuaUnsyncedCtrl::GiveOrderToUnit(lua_State * L){}
int CLuaUnsyncedCtrl::GiveOrderToUnitMap(lua_State * L){}
int CLuaUnsyncedCtrl::GiveOrderToUnitArray(lua_State * L){}
int CLuaUnsyncedCtrl::GiveOrderArrayToUnitMap(lua_State * L){}
int CLuaUnsyncedCtrl::GiveOrderArrayToUnitArray(lua_State * L){}
int CLuaUnsyncedCtrl::SendLuaUIMsg(lua_State * L){}
int CLuaUnsyncedCtrl::SendLuaGaiaMsg(lua_State * L){}
int CLuaUnsyncedCtrl::SendLuaRulesMsg(lua_State * L){}
int CLuaUnsyncedCtrl::SendLuaMenuMsg(lua_State * L){}
int CLuaUnsyncedCtrl::SetLastMessagePosition(lua_State * L){}
int CLuaUnsyncedCtrl::MarkerAddPoint(lua_State * L){}
int CLuaUnsyncedCtrl::MarkerAddLine(lua_State * L){}
int CLuaUnsyncedCtrl::MarkerErasePosition(lua_State * L){}
int CLuaUnsyncedCtrl::SetDrawSelectionInfo(lua_State * L){}
int CLuaUnsyncedCtrl::SetBuildSpacing(lua_State * L){}
int CLuaUnsyncedCtrl::SetBuildFacing(lua_State * L){}
int CLuaUnsyncedCtrl::SetAtmosphere(lua_State * L){}
int CLuaUnsyncedCtrl::SetSunLighting(lua_State * L){}
int CLuaUnsyncedCtrl::SetSunDirection(lua_State * L){}
int CLuaUnsyncedCtrl::SetMapRenderingParams(lua_State * L){}
int CLuaUnsyncedCtrl::SendSkirmishAIMessage(lua_State * L){}
int CLuaUnsyncedCtrl::SetLogSectionFilterLevel(lua_State * L){}
int CLuaUnsyncedCtrl::ClearWatchDogTimer(lua_State * L){}
int CLuaUnsyncedCtrl::PreloadUnitDefModel(lua_State * L){}
int CLuaUnsyncedCtrl::PreloadFeatureDefModel(lua_State * L){}
int CLuaUnsyncedCtrl::CreateDecal(lua_State * L){}
int CLuaUnsyncedCtrl::DestroyDecal(lua_State * L){}
int CLuaUnsyncedCtrl::SetDecalPos(lua_State * L){}
int CLuaUnsyncedCtrl::SetDecalSize(lua_State * L){}
int CLuaUnsyncedCtrl::SetDecalRotation(lua_State * L){}
int CLuaUnsyncedCtrl::SetDecalTexture(lua_State * L){}
int CLuaUnsyncedCtrl::SetDecalAlpha(lua_State * L){}
