// TODO: Substitue CLuaUnsyncedRead with your actual class name
bool CLuaUnsyncedRead::PushEntries(lua_State * L){}
int CLuaUnsyncedRead::IsReplay(lua_State * L){}
int CLuaUnsyncedRead::GetReplayLength(lua_State * L){}
int CLuaUnsyncedRead::GetGameName(lua_State * L){}
int CLuaUnsyncedRead::GetMenuName(lua_State * L){}
int CLuaUnsyncedRead::GetDrawFrame(lua_State * L){}
int CLuaUnsyncedRead::GetFrameTimeOffset(lua_State * L){}
int CLuaUnsyncedRead::GetLastUpdateSeconds(lua_State * L){}
int CLuaUnsyncedRead::GetHasLag(lua_State * L){}
int CLuaUnsyncedRead::GetVideoCapturingMode(lua_State * L){}
int CLuaUnsyncedRead::GetViewGeometry(lua_State * L){}
int CLuaUnsyncedRead::GetWindowGeometry(lua_State * L){}
int CLuaUnsyncedRead::GetScreenGeometry(lua_State * L){}
int CLuaUnsyncedRead::GetMiniMapGeometry(lua_State * L){}
int CLuaUnsyncedRead::GetMiniMapDualScreen(lua_State * L){}
int CLuaUnsyncedRead::IsAboveMiniMap(lua_State * L){}
int CLuaUnsyncedRead::IsAABBInView(lua_State * L){}
int CLuaUnsyncedRead::IsSphereInView(lua_State * L){}
int CLuaUnsyncedRead::IsUnitAllied(lua_State * L){}
int CLuaUnsyncedRead::IsUnitInView(lua_State * L){}
int CLuaUnsyncedRead::IsUnitVisible(lua_State * L){}
int CLuaUnsyncedRead::IsUnitIcon(lua_State * L){}
int CLuaUnsyncedRead::IsUnitSelected(lua_State * L){}
int CLuaUnsyncedRead::GetUnitLuaDraw(lua_State * L){}
int CLuaUnsyncedRead::GetUnitNoDraw(lua_State * L){}
int CLuaUnsyncedRead::GetUnitNoMinimap(lua_State * L){}
int CLuaUnsyncedRead::GetUnitNoSelect(lua_State * L){}
int CLuaUnsyncedRead::GetUnitSelectionVolumeData(lua_State * L){}
int CLuaUnsyncedRead::GetFeatureLuaDraw(lua_State * L){}
int CLuaUnsyncedRead::GetFeatureNoDraw(lua_State * L){}
int CLuaUnsyncedRead::GetFeatureSelectionVolumeData(lua_State * L){}
int CLuaUnsyncedRead::GetUnitTransformMatrix(lua_State * L){}
int CLuaUnsyncedRead::GetUnitViewPosition(lua_State * L){}
int CLuaUnsyncedRead::GetVisibleUnits(lua_State * L){}
int CLuaUnsyncedRead::GetVisibleFeatures(lua_State * L){}
int CLuaUnsyncedRead::GetVisibleProjectiles(lua_State * L){}
int CLuaUnsyncedRead::GetTeamColor(lua_State * L){}
int CLuaUnsyncedRead::GetTeamOrigColor(lua_State * L){}
int CLuaUnsyncedRead::GetLocalPlayerID(lua_State * L){}
int CLuaUnsyncedRead::GetLocalTeamID(lua_State * L){}
int CLuaUnsyncedRead::GetLocalAllyTeamID(lua_State * L){}
int CLuaUnsyncedRead::GetSpectatingState(lua_State * L){}
int CLuaUnsyncedRead::GetSelectedUnits(lua_State * L){}
int CLuaUnsyncedRead::GetSelectedUnitsSorted(lua_State * L){}
int CLuaUnsyncedRead::GetSelectedUnitsCounts(lua_State * L){}
int CLuaUnsyncedRead::GetSelectedUnitsCount(lua_State * L){}
int CLuaUnsyncedRead::IsGUIHidden(lua_State * L){}
int CLuaUnsyncedRead::HaveShadows(lua_State * L){}
int CLuaUnsyncedRead::HaveAdvShading(lua_State * L){}
int CLuaUnsyncedRead::GetWaterMode(lua_State * L){}
int CLuaUnsyncedRead::GetMapDrawMode(lua_State * L){}
int CLuaUnsyncedRead::GetMapSquareTexture(lua_State * L){}
int CLuaUnsyncedRead::GetLosViewColors(lua_State * L){}
int CLuaUnsyncedRead::GetCameraNames(lua_State * L){}
int CLuaUnsyncedRead::GetCameraState(lua_State * L){}
int CLuaUnsyncedRead::GetCameraPosition(lua_State * L){}
int CLuaUnsyncedRead::GetCameraDirection(lua_State * L){}
int CLuaUnsyncedRead::GetCameraFOV(lua_State * L){}
int CLuaUnsyncedRead::GetCameraVectors(lua_State * L){}
int CLuaUnsyncedRead::WorldToScreenCoords(lua_State * L){}
int CLuaUnsyncedRead::TraceScreenRay(lua_State * L){}
int CLuaUnsyncedRead::GetPixelDir(lua_State * L){}
int CLuaUnsyncedRead::GetTimer(lua_State * L){}
int CLuaUnsyncedRead::GetFrameTimer(lua_State * L){}
int CLuaUnsyncedRead::DiffTimers(lua_State * L){}
int CLuaUnsyncedRead::GetSoundStreamTime(lua_State * L){}
int CLuaUnsyncedRead::GetSoundEffectParams(lua_State * L){}
int CLuaUnsyncedRead::GetFPS(lua_State * L){}
int CLuaUnsyncedRead::GetGameSpeed(lua_State * L){}
int CLuaUnsyncedRead::GetMouseState(lua_State * L){}
int CLuaUnsyncedRead::GetMouseCursor(lua_State * L){}
int CLuaUnsyncedRead::GetMouseStartPosition(lua_State * L){}
int CLuaUnsyncedRead::GetKeyState(lua_State * L){}
int CLuaUnsyncedRead::GetModKeyState(lua_State * L){}
int CLuaUnsyncedRead::GetPressedKeys(lua_State * L){}
int CLuaUnsyncedRead::GetInvertQueueKey(lua_State * L){}
int CLuaUnsyncedRead::GetClipboard(lua_State * L){}
int CLuaUnsyncedRead::GetActiveCommand(lua_State * L){}
int CLuaUnsyncedRead::GetDefaultCommand(lua_State * L){}
int CLuaUnsyncedRead::GetActiveCmdDescs(lua_State * L){}
int CLuaUnsyncedRead::GetActiveCmdDesc(lua_State * L){}
int CLuaUnsyncedRead::GetCmdDescIndex(lua_State * L){}
int CLuaUnsyncedRead::GetGatherMode(lua_State * L){}
int CLuaUnsyncedRead::GetBuildFacing(lua_State * L){}
int CLuaUnsyncedRead::GetBuildSpacing(lua_State * L){}
int CLuaUnsyncedRead::GetActivePage(lua_State * L){}
int CLuaUnsyncedRead::GetLastMessagePositions(lua_State * L){}
int CLuaUnsyncedRead::GetConsoleBuffer(lua_State * L){}
int CLuaUnsyncedRead::GetCurrentTooltip(lua_State * L){}
int CLuaUnsyncedRead::GetKeyCode(lua_State * L){}
int CLuaUnsyncedRead::GetKeySymbol(lua_State * L){}
int CLuaUnsyncedRead::GetKeyBindings(lua_State * L){}
int CLuaUnsyncedRead::GetActionHotKeys(lua_State * L){}
int CLuaUnsyncedRead::GetGroupList(lua_State * L){}
int CLuaUnsyncedRead::GetSelectedGroup(lua_State * L){}
int CLuaUnsyncedRead::GetUnitGroup(lua_State * L){}
int CLuaUnsyncedRead::GetGroupUnits(lua_State * L){}
int CLuaUnsyncedRead::GetGroupUnitsSorted(lua_State * L){}
int CLuaUnsyncedRead::GetGroupUnitsCounts(lua_State * L){}
int CLuaUnsyncedRead::GetGroupUnitsCount(lua_State * L){}
int CLuaUnsyncedRead::GetPlayerRoster(lua_State * L){}
int CLuaUnsyncedRead::GetPlayerTraffic(lua_State * L){}
int CLuaUnsyncedRead::GetPlayerStatistics(lua_State * L){}
int CLuaUnsyncedRead::GetDrawSelectionInfo(lua_State * L){}
int CLuaUnsyncedRead::GetConfigParams(lua_State * L){}
int CLuaUnsyncedRead::GetLogSections(lua_State * L){}
int CLuaUnsyncedRead::GetAllDecals(lua_State * L){}
int CLuaUnsyncedRead::GetDecalPos(lua_State * L){}
int CLuaUnsyncedRead::GetDecalSize(lua_State * L){}
int CLuaUnsyncedRead::GetDecalRotation(lua_State * L){}
int CLuaUnsyncedRead::GetDecalTexture(lua_State * L){}
int CLuaUnsyncedRead::GetDecalAlpha(lua_State * L){}
int CLuaUnsyncedRead::GetDecalType(lua_State * L){}
int CLuaUnsyncedRead::GetDecalOwner(lua_State * L){}
