// TODO: Substitue CGlobalConstants with your actual class name
int CGlobalConstants::SQUARE_SIZE(){}
int CGlobalConstants::SPRING_FOOTPRINT_SCALE(){}
float CGlobalConstants::ELMOS_TO_METERS(){}
int CGlobalConstants::GAME_SPEED(){}
int CGlobalConstants::UNIT_SLOWUPDATE_RATE(){}
int CGlobalConstants::TEAM_SLOWUPDATE_RATE(){}
int CGlobalConstants::LOS_TERRAFORM_SLOWUPDATE_RATE(){}
int CGlobalConstants::MAX_TEAMS(){}
int CGlobalConstants::MAX_PLAYERS(){}
int CGlobalConstants::MAX_AIS(){}
int CGlobalConstants::MAX_UNITS(){}
int CGlobalConstants::MAX_FEATURES(){}
int CGlobalConstants::MAX_PROJECTILES(){}
int CGlobalConstants::MAX_WEAPONS_PER_UNIT(){}
float CGlobalConstants::MAX_UNIT_SPEED(){}
float CGlobalConstants::MAX_EXPLOSION_IMPULSE(){}
float CGlobalConstants::DIRECT_EXPLOSION_DAMAGE_SPEED_SCALE(){}
float CGlobalConstants::MAX_PROJECTILE_RANGE(){}
float CGlobalConstants::MAX_PROJECTILE_HEIGHT(){}
int CGlobalConstants::MAX_UNIT_SENSOR_RADIUS(){}
