// TODO: Substitue CBlenderScene with your actual class name
q(const).size_t CBlenderScene::Assimp::Blender::MaxNameLen(){}
char CBlenderScene::name(){}
short CBlenderScene::flag(){}
std::shared_ptr<(ElemBase)> CBlenderScene::first(){}
std::shared_ptr<(ElemBase)> CBlenderScene::last(){}
int CBlenderScene::size(){}
int CBlenderScene::seek(){}
std::shared_ptr<(FileOffset)> CBlenderScene::data(){}
std::shared_ptr<(Assimp::Blender::GroupObject)> CBlenderScene::prev(){}
std::shared_ptr<(Assimp::Blender::GroupObject)> CBlenderScene::next(){}
std::shared_ptr<(Assimp::Blender::Object)> CBlenderScene::ob(){}
Assimp::Blender::ID CBlenderScene::id(){}
int CBlenderScene::layer(){}
std::shared_ptr<(Assimp::Blender::GroupObject)> CBlenderScene::gobject(){}
Assimp::Blender::ID CBlenderScene::id(){}
float CBlenderScene::co(){}
float CBlenderScene::no(){}
char CBlenderScene::flag(){}
int CBlenderScene::mat_nr(){}
int CBlenderScene::bweight(){}
int CBlenderScene::v1(){}
int CBlenderScene::v2(){}
char CBlenderScene::crease(){}
char CBlenderScene::bweight(){}
short CBlenderScene::flag(){}
int CBlenderScene::v(){}
int CBlenderScene::e(){}
float CBlenderScene::uv(){}
int CBlenderScene::flag(){}
unsigned char CBlenderScene::r(){}
unsigned char CBlenderScene::g(){}
unsigned char CBlenderScene::b(){}
unsigned char CBlenderScene::a(){}
int CBlenderScene::loopstart(){}
int CBlenderScene::totloop(){}
short CBlenderScene::mat_nr(){}
char CBlenderScene::flag(){}
Assimp::Blender::Image CBlenderScene::tpage(){}
char CBlenderScene::flag(){}
char CBlenderScene::transp(){}
short CBlenderScene::mode(){}
short CBlenderScene::tile(){}
short CBlenderScene::pad(){}
char CBlenderScene::r(){}
char CBlenderScene::g(){}
char CBlenderScene::b(){}
char CBlenderScene::a(){}
int CBlenderScene::v1(){}
int CBlenderScene::v2(){}
int CBlenderScene::v3(){}
int CBlenderScene::v4(){}
int CBlenderScene::mat_nr(){}
char CBlenderScene::flag(){}
float CBlenderScene::uv(){}
int CBlenderScene::col(){}
char CBlenderScene::flag(){}
short CBlenderScene::mode(){}
short CBlenderScene::tile(){}
short CBlenderScene::unwrap(){}
float CBlenderScene::uv(){}
char CBlenderScene::flag(){}
short CBlenderScene::mode(){}
short CBlenderScene::tile(){}
short CBlenderScene::unwrap(){}
int CBlenderScene::def_nr(){}
float CBlenderScene::weight(){}
vector<(Assimp::Blender::MDeformWeight)> CBlenderScene::dw(){}
int CBlenderScene::totweight(){}
Assimp::Blender::ID CBlenderScene::id(){}
float CBlenderScene::r(){}
float CBlenderScene::g(){}
float CBlenderScene::b(){}
float CBlenderScene::specr(){}
float CBlenderScene::specg(){}
float CBlenderScene::specb(){}
short CBlenderScene::har(){}
float CBlenderScene::ambr(){}
float CBlenderScene::ambg(){}
float CBlenderScene::ambb(){}
float CBlenderScene::mirr(){}
float CBlenderScene::mirg(){}
float CBlenderScene::mirb(){}
float CBlenderScene::emit(){}
float CBlenderScene::ray_mirror(){}
float CBlenderScene::alpha(){}
float CBlenderScene::ref(){}
float CBlenderScene::translucency(){}
int CBlenderScene::mode(){}
float CBlenderScene::roughness(){}
float CBlenderScene::darkness(){}
float CBlenderScene::refrac(){}
float CBlenderScene::amb(){}
float CBlenderScene::ang(){}
float CBlenderScene::spectra(){}
float CBlenderScene::spec(){}
float CBlenderScene::zoffs(){}
float CBlenderScene::add(){}
float CBlenderScene::fresnel_mir(){}
float CBlenderScene::fresnel_mir_i(){}
float CBlenderScene::fresnel_tra(){}
float CBlenderScene::fresnel_tra_i(){}
float CBlenderScene::filter(){}
float CBlenderScene::tx_limit(){}
float CBlenderScene::tx_falloff(){}
float CBlenderScene::gloss_mir(){}
float CBlenderScene::gloss_tra(){}
float CBlenderScene::adapt_thresh_mir(){}
float CBlenderScene::adapt_thresh_tra(){}
float CBlenderScene::aniso_gloss_mir(){}
float CBlenderScene::dist_mir(){}
float CBlenderScene::hasize(){}
float CBlenderScene::flaresize(){}
float CBlenderScene::subsize(){}
float CBlenderScene::flareboost(){}
float CBlenderScene::strand_sta(){}
float CBlenderScene::strand_end(){}
float CBlenderScene::strand_ease(){}
float CBlenderScene::strand_surfnor(){}
float CBlenderScene::strand_min(){}
float CBlenderScene::strand_widthfade(){}
float CBlenderScene::sbias(){}
float CBlenderScene::lbias(){}
float CBlenderScene::shad_alpha(){}
float CBlenderScene::param(){}
float CBlenderScene::rms(){}
float CBlenderScene::rampfac_col(){}
float CBlenderScene::rampfac_spec(){}
float CBlenderScene::friction(){}
float CBlenderScene::fh(){}
float CBlenderScene::reflect(){}
float CBlenderScene::fhdist(){}
float CBlenderScene::xyfrict(){}
float CBlenderScene::sss_radius(){}
float CBlenderScene::sss_col(){}
float CBlenderScene::sss_error(){}
float CBlenderScene::sss_scale(){}
float CBlenderScene::sss_ior(){}
float CBlenderScene::sss_colfac(){}
float CBlenderScene::sss_texfac(){}
float CBlenderScene::sss_front(){}
float CBlenderScene::sss_back(){}
short CBlenderScene::material_type(){}
short CBlenderScene::flag(){}
short CBlenderScene::ray_depth(){}
short CBlenderScene::ray_depth_tra(){}
short CBlenderScene::samp_gloss_mir(){}
short CBlenderScene::samp_gloss_tra(){}
short CBlenderScene::fadeto_mir(){}
short CBlenderScene::shade_flag(){}
short CBlenderScene::flarec(){}
short CBlenderScene::starc(){}
short CBlenderScene::linec(){}
short CBlenderScene::ringc(){}
short CBlenderScene::pr_lamp(){}
short CBlenderScene::pr_texture(){}
short CBlenderScene::ml_flag(){}
short CBlenderScene::texco(){}
short CBlenderScene::mapto(){}
short CBlenderScene::ramp_show(){}
short CBlenderScene::pad3(){}
short CBlenderScene::dynamode(){}
short CBlenderScene::pad2(){}
short CBlenderScene::sss_flag(){}
short CBlenderScene::sss_preset(){}
short CBlenderScene::shadowonly_flag(){}
short CBlenderScene::index(){}
short CBlenderScene::vcol_alpha(){}
short CBlenderScene::pad4(){}
char CBlenderScene::seed1(){}
char CBlenderScene::seed2(){}
std::shared_ptr<(Assimp::Blender::Group)> CBlenderScene::group(){}
short CBlenderScene::diff_shader(){}
short CBlenderScene::spec_shader(){}
std::shared_ptr<(Assimp::Blender::MTex)> CBlenderScene::mtex(){}
Assimp::Blender::ID CBlenderScene::id(){}
int CBlenderScene::totface(){}
int CBlenderScene::totedge(){}
int CBlenderScene::totvert(){}
int CBlenderScene::totloop(){}
int CBlenderScene::totpoly(){}
short CBlenderScene::subdiv(){}
short CBlenderScene::subdivr(){}
short CBlenderScene::subsurftype(){}
short CBlenderScene::smoothresh(){}
vector<(Assimp::Blender::MFace)> CBlenderScene::mface(){}
vector<(Assimp::Blender::MTFace)> CBlenderScene::mtface(){}
vector<(Assimp::Blender::TFace)> CBlenderScene::tface(){}
vector<(Assimp::Blender::MVert)> CBlenderScene::mvert(){}
vector<(Assimp::Blender::MEdge)> CBlenderScene::medge(){}
vector<(Assimp::Blender::MLoop)> CBlenderScene::mloop(){}
vector<(Assimp::Blender::MLoopUV)> CBlenderScene::mloopuv(){}
vector<(Assimp::Blender::MLoopCol)> CBlenderScene::mloopcol(){}
vector<(Assimp::Blender::MPoly)> CBlenderScene::mpoly(){}
vector<(Assimp::Blender::MTexPoly)> CBlenderScene::mtpoly(){}
vector<(Assimp::Blender::MDeformVert)> CBlenderScene::dvert(){}
vector<(Assimp::Blender::MCol)> CBlenderScene::mcol(){}
vector<(std::shared_ptr<(Assimp::Blender::Material)>)> CBlenderScene::mat(){}
Assimp::Blender::ID CBlenderScene::id(){}
char CBlenderScene::name(){}
char CBlenderScene::filename(){}
std::shared_ptr<(Assimp::Blender::Library)> CBlenderScene::parent(){}
Assimp::Blender::ID CBlenderScene::id(){}
Assimp::Blender::Camera::Type CBlenderScene::type(){}
Assimp::Blender::Camera::Type CBlenderScene::flag(){}
float CBlenderScene::lens(){}
float CBlenderScene::sensor_x(){}
float CBlenderScene::clipsta(){}
float CBlenderScene::clipend(){}
Assimp::Blender::ID CBlenderScene::id(){}
Assimp::Blender::Lamp::Type CBlenderScene::type(){}
short CBlenderScene::flags(){}
short CBlenderScene::colormodel(){}
short CBlenderScene::totex(){}
float CBlenderScene::r(){}
float CBlenderScene::g(){}
float CBlenderScene::b(){}
float CBlenderScene::k(){}
float CBlenderScene::energy(){}
float CBlenderScene::dist(){}
float CBlenderScene::spotsize(){}
float CBlenderScene::spotblend(){}
float CBlenderScene::att1(){}
float CBlenderScene::att2(){}
Assimp::Blender::Lamp::FalloffType CBlenderScene::falloff_type(){}
short CBlenderScene::area_shape(){}
float CBlenderScene::area_size(){}
float CBlenderScene::area_sizey(){}
float CBlenderScene::area_sizez(){}
float CBlenderScene::sun_brightness(){}
std::shared_ptr<(ElemBase)> CBlenderScene::next(){}
std::shared_ptr<(ElemBase)> CBlenderScene::prev(){}
int CBlenderScene::type(){}
int CBlenderScene::mode(){}
char CBlenderScene::name(){}
Assimp::Blender::ModifierData CBlenderScene::modifier(){}
short CBlenderScene::subdivType(){}
short CBlenderScene::levels(){}
short CBlenderScene::renderLevels(){}
short CBlenderScene::flags(){}
Assimp::Blender::ModifierData CBlenderScene::modifier(){}
short CBlenderScene::axis(){}
short CBlenderScene::flag(){}
float CBlenderScene::tolerance(){}
std::shared_ptr<(Assimp::Blender::Object)> CBlenderScene::mirror_ob(){}
Assimp::Blender::ID CBlenderScene::id(){}
Assimp::Blender::Object::Type CBlenderScene::type(){}
float CBlenderScene::obmat(){}
float CBlenderScene::parentinv(){}
char CBlenderScene::parsubstr(){}
Assimp::Blender::Object CBlenderScene::parent(){}
std::shared_ptr<(Assimp::Blender::Object)> CBlenderScene::track(){}
std::shared_ptr<(Assimp::Blender::Object)> CBlenderScene::proxy(){}
std::shared_ptr<(Assimp::Blender::Object)> CBlenderScene::proxy_from(){}
std::shared_ptr<(Assimp::Blender::Object)> CBlenderScene::proxy_group(){}
std::shared_ptr<(Assimp::Blender::Group)> CBlenderScene::dup_group(){}
std::shared_ptr<(ElemBase)> CBlenderScene::data(){}
Assimp::Blender::ListBase CBlenderScene::modifiers(){}
Assimp::Blender::Base CBlenderScene::prev(){}
std::shared_ptr<(Assimp::Blender::Base)> CBlenderScene::next(){}
std::shared_ptr<(Assimp::Blender::Object)> CBlenderScene::object(){}
Assimp::Blender::ID CBlenderScene::id(){}
std::shared_ptr<(Assimp::Blender::Object)> CBlenderScene::camera(){}
std::shared_ptr<(Assimp::Blender::World)> CBlenderScene::world(){}
std::shared_ptr<(Assimp::Blender::Base)> CBlenderScene::basact(){}
Assimp::Blender::ListBase CBlenderScene::base(){}
Assimp::Blender::ID CBlenderScene::id(){}
char CBlenderScene::name(){}
short CBlenderScene::ok(){}
short CBlenderScene::flag(){}
short CBlenderScene::source(){}
short CBlenderScene::type(){}
short CBlenderScene::pad(){}
short CBlenderScene::pad1(){}
int CBlenderScene::lastframe(){}
short CBlenderScene::tpageflag(){}
short CBlenderScene::totbind(){}
short CBlenderScene::xrep(){}
short CBlenderScene::yrep(){}
short CBlenderScene::twsta(){}
short CBlenderScene::twend(){}
std::shared_ptr<(Assimp::Blender::PackedFile)> CBlenderScene::packedfile(){}
float CBlenderScene::lastupdate(){}
int CBlenderScene::lastused(){}
short CBlenderScene::animspeed(){}
short CBlenderScene::gen_x(){}
short CBlenderScene::gen_y(){}
short CBlenderScene::gen_type(){}
Assimp::Blender::ID CBlenderScene::id(){}
Assimp::Blender::Tex::ImageFlags CBlenderScene::imaflag(){}
Assimp::Blender::Tex::Type CBlenderScene::type(){}
std::shared_ptr<(Assimp::Blender::Image)> CBlenderScene::ima(){}
Assimp::Blender::MTex::MapType CBlenderScene::mapto(){}
Assimp::Blender::MTex::BlendType CBlenderScene::blendtype(){}
std::shared_ptr<(Assimp::Blender::Object)> CBlenderScene::object(){}
std::shared_ptr<(Assimp::Blender::Tex)> CBlenderScene::tex(){}
char CBlenderScene::uvname(){}
Assimp::Blender::MTex::Projection CBlenderScene::projx(){}
Assimp::Blender::MTex::Projection CBlenderScene::projy(){}
Assimp::Blender::MTex::Projection CBlenderScene::projz(){}
char CBlenderScene::mapping(){}
float CBlenderScene::ofs(){}
float CBlenderScene::size(){}
float CBlenderScene::rot(){}
int CBlenderScene::texflag(){}
short CBlenderScene::colormodel(){}
short CBlenderScene::pmapto(){}
short CBlenderScene::pmaptoneg(){}
float CBlenderScene::r(){}
float CBlenderScene::g(){}
float CBlenderScene::b(){}
float CBlenderScene::k(){}
float CBlenderScene::norfac(){}
float CBlenderScene::colspecfac(){}
float CBlenderScene::mirrfac(){}
float CBlenderScene::alphafac(){}
float CBlenderScene::difffac(){}
float CBlenderScene::specfac(){}
float CBlenderScene::emitfac(){}
float CBlenderScene::hardfac(){}
