// TODO: Substitue CHalfLifeFileData with your actual class name
char CHalfLifeFileData::ident(){}
int32_t CHalfLifeFileData::version(){}
char CHalfLifeFileData::name(){}
int32_t CHalfLifeFileData::length(){}
aiVector3D CHalfLifeFileData::eyeposition(){}
aiVector3D CHalfLifeFileData::min(){}
aiVector3D CHalfLifeFileData::max(){}
aiVector3D CHalfLifeFileData::bbmin(){}
aiVector3D CHalfLifeFileData::bbmax(){}
int32_t CHalfLifeFileData::flags(){}
int32_t CHalfLifeFileData::numbones(){}
int32_t CHalfLifeFileData::boneindex(){}
int32_t CHalfLifeFileData::numbonecontrollers(){}
int32_t CHalfLifeFileData::bonecontrollerindex(){}
int32_t CHalfLifeFileData::numhitboxes(){}
int32_t CHalfLifeFileData::hitboxindex(){}
int32_t CHalfLifeFileData::numseq(){}
int32_t CHalfLifeFileData::seqindex(){}
int32_t CHalfLifeFileData::numseqgroups(){}
int32_t CHalfLifeFileData::seqgroupindex(){}
int32_t CHalfLifeFileData::numtextures(){}
int32_t CHalfLifeFileData::textureindex(){}
int32_t CHalfLifeFileData::texturedataindex(){}
int32_t CHalfLifeFileData::numskinref(){}
int32_t CHalfLifeFileData::numskinfamilies(){}
int32_t CHalfLifeFileData::skinindex(){}
int32_t CHalfLifeFileData::numbodyparts(){}
int32_t CHalfLifeFileData::bodypartindex(){}
int32_t CHalfLifeFileData::numattachments(){}
int32_t CHalfLifeFileData::attachmentindex(){}
int32_t CHalfLifeFileData::soundtable(){}
int32_t CHalfLifeFileData::soundindex(){}
int32_t CHalfLifeFileData::soundgroups(){}
int32_t CHalfLifeFileData::soundgroupindex(){}
int32_t CHalfLifeFileData::numtransitions(){}
int32_t CHalfLifeFileData::transitionindex(){}
Assimp::MDL::Header_HL2 CHalfLifeFileData::Assimp::MDL::PACK_STRUCT(){}
