// TODO: Substitue CAILegacySupport with your actual class name
float CAILegacySupport::metalUse(){}
float CAILegacySupport::energyUse(){}
float CAILegacySupport::metalMake(){}
float CAILegacySupport::energyMake(){}
float3 CAILegacySupport::pos(){}
SColor CAILegacySupport::color(){}
q(const).char CAILegacySupport::label(){}
float3 CAILegacySupport::pos(){}
float3 CAILegacySupport::pos2(){}
SColor CAILegacySupport::color(){}
float3 CAILegacySupport::pos(){}
q(const).char CAILegacySupport::label(){}
float3 CAILegacySupport::posfrom(){}
float3 CAILegacySupport::posto(){}
float3 CAILegacySupport::pos(){}
bool CAILegacySupport::ready(){}
float3 CAILegacySupport::pos(){}
int CAILegacySupport::unitDefId(){}
q(const).UnitDef CAILegacySupport::ret(){}
int CAILegacySupport::weaponDefId(){}
q(const).WeaponDef CAILegacySupport::ret(){}
int CAILegacySupport::featureDefId(){}
q(const).FeatureDef CAILegacySupport::ret(){}
float3 CAILegacySupport::rayPos(){}
float3 CAILegacySupport::rayDir(){}
float CAILegacySupport::rayLen(){}
int CAILegacySupport::srcUID(){}
int CAILegacySupport::hitUID(){}
int CAILegacySupport::flags(){}
float3 CAILegacySupport::rayPos(){}
float3 CAILegacySupport::rayDir(){}
float CAILegacySupport::rayLen(){}
int CAILegacySupport::srcUID(){}
int CAILegacySupport::hitFID(){}
int CAILegacySupport::flags(){}
bool CAILegacySupport::enable(){}
q(const).char CAILegacySupport::reason(){}
q(const).char CAILegacySupport::relPath(){}
bool CAILegacySupport::writeable(){}
bool CAILegacySupport::create(){}
bool CAILegacySupport::dir(){}
bool CAILegacySupport::common(){}
char CAILegacySupport::ret_path(){}
int CAILegacySupport::cmdMode(){}
float CAILegacySupport::x(){}
float CAILegacySupport::y(){}
float CAILegacySupport::w(){}
float CAILegacySupport::h(){}
int CAILegacySupport::lineId(){}
int CAILegacySupport::numPoints(){}
float3 CAILegacySupport::color(){}
std::string CAILegacySupport::label(){}
int CAILegacySupport::texHandle(){}
q(const).float CAILegacySupport::texData(){}
