// TODO: Substitue Cs3o with your actual class name
int Cs3o::name(){}
int Cs3o::numchildren(){}
int Cs3o::children(){}
int Cs3o::numVertices(){}
int Cs3o::vertices(){}
int Cs3o::vertexType(){}
int Cs3o::primitiveType(){}
int Cs3o::vertexTableSize(){}
int Cs3o::vertexTable(){}
int Cs3o::collisionData(){}
float Cs3o::xoffset(){}
float Cs3o::yoffset(){}
float Cs3o::zoffset(){}
float Cs3o::xpos(){}
float Cs3o::ypos(){}
float Cs3o::zpos(){}
float Cs3o::xnormal(){}
float Cs3o::ynormal(){}
float Cs3o::znormal(){}
float Cs3o::texu(){}
float Cs3o::texv(){}
char Cs3o::magic(){}
int Cs3o::version(){}
float Cs3o::radius(){}
float Cs3o::height(){}
float Cs3o::midx(){}
float Cs3o::midy(){}
float Cs3o::midz(){}
int Cs3o::rootPiece(){}
int Cs3o::collisionData(){}
int Cs3o::texture1(){}
int Cs3o::texture2(){}
