// TODO: Substitue CMsgStrings with your actual class name
q(const).std::string CMsgStrings::ServerStart(){}
q(const).std::string CMsgStrings::PlayingDemo(){}
q(const).std::string CMsgStrings::ConnectAutohost(){}
q(const).std::string CMsgStrings::ConnectAutohostFailed(){}
q(const).std::string CMsgStrings::DemoStart(){}
q(const).std::string CMsgStrings::DemoEnd(){}
q(const).std::string CMsgStrings::GameEnd(){}
q(const).std::string CMsgStrings::NoClientsExit(){}
q(const).std::string CMsgStrings::NoSyncResponse(){}
q(const).std::string CMsgStrings::SyncError(){}
q(const).std::string CMsgStrings::NoSyncCheck(){}
q(const).std::string CMsgStrings::ConnectionReject(){}
q(const).std::string CMsgStrings::WrongPlayer(){}
q(const).std::string CMsgStrings::PlayerJoined(){}
q(const).std::string CMsgStrings::PlayerLeft(){}
q(const).std::string CMsgStrings::PlayerResigned(){}
q(const).std::string CMsgStrings::NoStartposChange(){}
q(const).std::string CMsgStrings::NoHelperAI(){}
q(const).std::string CMsgStrings::NoTeamChange(){}
q(const).std::string CMsgStrings::NoAICreated(){}
q(const).std::string CMsgStrings::NoAIChangeState(){}
q(const).std::string CMsgStrings::UnknownTeammsg(){}
q(const).std::string CMsgStrings::UnknownNetmsg(){}
q(const).std::string CMsgStrings::CommandNotAllowed(){}
q(const).std::string CMsgStrings::UncontrolledPlayerName(){}
q(const).std::string CMsgStrings::UnnamedPlayerName(){}
