// TODO: Substitue CAISCommands with your actual class name
q(const).int CAISCommands::NUM_CMD_TOPICS(){}
float CAISCommands::factor(){}
int CAISCommands::resourceId(){}
float CAISCommands::amount(){}
int CAISCommands::unitDefId(){}
float CAISCommands::pos_posF3(){}
int CAISCommands::ret_newUnitId(){}
q(const).char CAISCommands::text(){}
int CAISCommands::zone(){}
float CAISCommands::pos_posF3(){}
int CAISCommands::resourceId(){}
float CAISCommands::amount(){}
int CAISCommands::receivingTeamId(){}
bool CAISCommands::ret_isExecuted(){}
int CAISCommands::unitIds(){}
int CAISCommands::unitIds_size(){}
int CAISCommands::receivingTeamId(){}
int CAISCommands::ret_sentUnits(){}
int CAISCommands::ret_groupId(){}
int CAISCommands::groupId(){}
float CAISCommands::start_posF3(){}
float CAISCommands::end_posF3(){}
int CAISCommands::pathType(){}
float CAISCommands::goalRadius(){}
int CAISCommands::ret_pathId(){}
float CAISCommands::start_posF3(){}
float CAISCommands::end_posF3(){}
int CAISCommands::pathType(){}
float CAISCommands::goalRadius(){}
float CAISCommands::ret_approximatePathLength(){}
int CAISCommands::pathId(){}
float CAISCommands::ret_nextWaypoint_posF3_out(){}
int CAISCommands::pathId(){}
q(const).char CAISCommands::inData(){}
int CAISCommands::inSize(){}
char CAISCommands::ret_outData(){}
q(const).char CAISCommands::inData(){}
int CAISCommands::inSize(){}
char CAISCommands::ret_outData(){}
bool CAISCommands::ready(){}
float CAISCommands::pos_posF3(){}
float CAISCommands::pos_posF3(){}
short CAISCommands::color_colorS3(){}
short CAISCommands::alpha(){}
float CAISCommands::pos_posF3(){}
q(const).char CAISCommands::label(){}
float CAISCommands::pos_posF3(){}
float CAISCommands::posFrom_posF3(){}
float CAISCommands::posTo_posF3(){}
float CAISCommands::pos_posF3(){}
short CAISCommands::color_colorS3(){}
short CAISCommands::alpha(){}
bool CAISCommands::iAmUseless(){}
float CAISCommands::endPos_posF3(){}
short CAISCommands::color_colorS3(){}
short CAISCommands::alpha(){}
int CAISCommands::cmdId(){}
float CAISCommands::endPos_posF3(){}
short CAISCommands::color_colorS3(){}
short CAISCommands::alpha(){}
int CAISCommands::cmdId(){}
float CAISCommands::endPos_posF3(){}
short CAISCommands::color_colorS3(){}
short CAISCommands::alpha(){}
bool CAISCommands::sameColor(){}
float CAISCommands::pos1_posF3(){}
float CAISCommands::pos2_posF3(){}
float CAISCommands::pos3_posF3(){}
float CAISCommands::pos4_posF3(){}
float CAISCommands::width(){}
bool CAISCommands::arrow(){}
int CAISCommands::lifeTime(){}
int CAISCommands::figureGroupId(){}
int CAISCommands::ret_newFigureGroupId(){}
float CAISCommands::pos1_posF3(){}
float CAISCommands::pos2_posF3(){}
float CAISCommands::width(){}
bool CAISCommands::arrow(){}
int CAISCommands::lifeTime(){}
int CAISCommands::figureGroupId(){}
int CAISCommands::ret_newFigureGroupId(){}
int CAISCommands::figureGroupId(){}
short CAISCommands::color_colorS3(){}
short CAISCommands::alpha(){}
int CAISCommands::figureGroupId(){}
int CAISCommands::toDrawUnitDefId(){}
float CAISCommands::pos_posF3(){}
float CAISCommands::rotation(){}
int CAISCommands::lifeTime(){}
int CAISCommands::teamId(){}
bool CAISCommands::transparent(){}
bool CAISCommands::drawBorder(){}
int CAISCommands::facing(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::toBuildUnitDefId(){}
float CAISCommands::buildPos_posF3(){}
int CAISCommands::facing(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::time(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::toDieUnitId(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::numUnits(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
float CAISCommands::toPos_posF3(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
float CAISCommands::toPos_posF3(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
float CAISCommands::toPos_posF3(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::toAttackUnitId(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
float CAISCommands::toAttackPos_posF3(){}
float CAISCommands::radius(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::toGuardUnitId(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::toGroupId(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::toRepairUnitId(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::fireState(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::moveState(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
float CAISCommands::basePos_posF3(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
float CAISCommands::wantedMaxSpeed(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::toLoadUnitIds(){}
int CAISCommands::toLoadUnitIds_size(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
float CAISCommands::pos_posF3(){}
float CAISCommands::radius(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::transporterUnitId(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
float CAISCommands::toPos_posF3(){}
int CAISCommands::toUnloadUnitId(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
float CAISCommands::toPos_posF3(){}
float CAISCommands::radius(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
bool CAISCommands::on(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::toReclaimUnitId(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::toReclaimFeatureId(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
float CAISCommands::pos_posF3(){}
float CAISCommands::radius(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
bool CAISCommands::cloak(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::toAttackUnitId(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
float CAISCommands::pos_posF3(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
float CAISCommands::pos_posF3(){}
float CAISCommands::radius(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
bool CAISCommands::repeat(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::trajectory(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::toResurrectFeatureId(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
float CAISCommands::pos_posF3(){}
float CAISCommands::radius(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::toCaptureUnitId(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
float CAISCommands::pos_posF3(){}
float CAISCommands::radius(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::autoRepairLevel(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::idleMode(){}
int CAISCommands::unitId(){}
int CAISCommands::groupId(){}
short CAISCommands::options(){}
int CAISCommands::timeOut(){}
int CAISCommands::cmdId(){}
float CAISCommands::params(){}
int CAISCommands::params_size(){}
float CAISCommands::rayPos_posF3(){}
float CAISCommands::rayDir_posF3(){}
float CAISCommands::rayLen(){}
int CAISCommands::srcUnitId(){}
int CAISCommands::ret_hitUnitId(){}
int CAISCommands::flags(){}
float CAISCommands::rayPos_posF3(){}
float CAISCommands::rayDir_posF3(){}
float CAISCommands::rayLen(){}
int CAISCommands::srcUnitId(){}
int CAISCommands::ret_hitFeatureId(){}
int CAISCommands::flags(){}
bool CAISCommands::enable(){}
q(const).char CAISCommands::reason(){}
float CAISCommands::x(){}
float CAISCommands::y(){}
float CAISCommands::w(){}
float CAISCommands::h(){}
int CAISCommands::lineId(){}
float CAISCommands::x(){}
float CAISCommands::y(){}
int CAISCommands::lineId(){}
int CAISCommands::numPoints(){}
int CAISCommands::lineId(){}
short CAISCommands::color_colorS3(){}
int CAISCommands::lineId(){}
q(const).char CAISCommands::label(){}
int CAISCommands::ret_overlayTextureId(){}
q(const).float CAISCommands::texData(){}
int CAISCommands::w(){}
int CAISCommands::h(){}
int CAISCommands::overlayTextureId(){}
q(const).float CAISCommands::texData(){}
int CAISCommands::x(){}
int CAISCommands::y(){}
int CAISCommands::w(){}
int CAISCommands::h(){}
int CAISCommands::overlayTextureId(){}
int CAISCommands::overlayTextureId(){}
float CAISCommands::x(){}
float CAISCommands::y(){}
int CAISCommands::overlayTextureId(){}
float CAISCommands::w(){}
float CAISCommands::h(){}
int CAISCommands::overlayTextureId(){}
q(const).char CAISCommands::label(){}
int CAISCommands::toInternalUnitCommandTopic(int aiCmdTopic, void * sUnitCommandData){}
int CAISCommands::extractAICommandTopic(const Command * internalUnitCmd, int maxUnits){}
bool CAISCommands::newCommand(void * sUnitCommandData, int sCommandId, int maxUnits, Command * c){}
