// TODO: Substitue CAISEvents with your actual class name
q(const).int CAISEvents::NUM_EVENTS(){}
int CAISEvents::skirmishAIId(){}
q(const).SSkirmishAICallback CAISEvents::callback(){}
int CAISEvents::reason(){}
int CAISEvents::frame(){}
int CAISEvents::player(){}
q(const).char CAISEvents::message(){}
q(const).char CAISEvents::inData(){}
int CAISEvents::unit(){}
int CAISEvents::builder(){}
int CAISEvents::unit(){}
int CAISEvents::unit(){}
int CAISEvents::unit(){}
int CAISEvents::unit(){}
int CAISEvents::attacker(){}
float CAISEvents::damage(){}
float CAISEvents::dir_posF3(){}
int CAISEvents::weaponDefId(){}
bool CAISEvents::paralyzer(){}
int CAISEvents::unit(){}
int CAISEvents::attacker(){}
int CAISEvents::unitId(){}
int CAISEvents::oldTeamId(){}
int CAISEvents::newTeamId(){}
int CAISEvents::unitId(){}
int CAISEvents::oldTeamId(){}
int CAISEvents::newTeamId(){}
int CAISEvents::enemy(){}
int CAISEvents::enemy(){}
int CAISEvents::enemy(){}
int CAISEvents::enemy(){}
int CAISEvents::enemy(){}
int CAISEvents::attacker(){}
float CAISEvents::damage(){}
float CAISEvents::dir_posF3(){}
int CAISEvents::weaponDefId(){}
bool CAISEvents::paralyzer(){}
int CAISEvents::enemy(){}
int CAISEvents::attacker(){}
int CAISEvents::unitId(){}
int CAISEvents::weaponDefId(){}
int CAISEvents::unitIds(){}
int CAISEvents::unitIds_size(){}
int CAISEvents::commandTopicId(){}
int CAISEvents::playerId(){}
int CAISEvents::unitId(){}
int CAISEvents::commandId(){}
int CAISEvents::commandTopicId(){}
float CAISEvents::pos_posF3(){}
float CAISEvents::strength(){}
q(const).char CAISEvents::file(){}
q(const).char CAISEvents::file(){}
int CAISEvents::enemy(){}
int CAISEvents::enemy(){}
